before_install:
- sudo apt-get update
- sudo apt-get install debhelper python dh-autoreconf python-support python-git devscripts
- set |grep -v pgpassword
- export PGPKEY=804609ED
- export DEBEMAIL="Travis Zorp <mag+travis@magwas.rulez.org>"
script:
- ./src/sinz.py deb buildAndDput precise
env:
  global:
    secure: k+Fk1lHV3hV7wgTcoEF5KfySSKqRaGXIoTdN6zC0jArAckB8vj24M4wnSXfzaZqw9zuHwsmddqMlDV02OFKZz99NvuPvN28v1/z0P7K0nIXCaCq5jPRAUagi0tHVunYV9Vus8eDZqOs8cq4sEWghH20MNbrV78e5nSuo6NrkPeg=
