before_install:
- sudo apt-get update
- sudo apt-get install debhelper python dh-autoreconf python-support python-git devscripts
- set |grep -v pgpassword
- export PGPKEY=804609ED
script:
- ./src/sinz.py deb buildAndDput
env:
  global:
    secure: ozNosfVxt+lO5EWLmwIdKCFhNQFtl6s3l0NDBVoqIFLv9hkL1OZDW/63tfGBBrWGfvO7s0csn2ChWmBMpkUSlU5Gp3MkZOtQ/lsFFBIEI7efHnWQRXsxyHO592It9e5bf0whDKoRZQ3AhgdexHtBXlfE6/CcfSQqhu5QhwTusG8=
